# 应用名称
spring:
  application:
    name: xyt
    # 数据库相关配置
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/xyt?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      maximum-pool-size: 2
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
server:
  # 服务端口
  port: 8888
  # 服务地址
# 整合Mybatis-plus 配置
mybatis-plus:
  type-aliases-package: com.zj.xyt.Entity
  mapper-locations: classpath:mapper/*.xml

