# 应用名称
spring:
  application:
    name: xyt
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/xyt?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  # 服务端口
  port: 8888
  # 服务地址
  # 数据库相关配置
# 整合Mybatis-plus 配置
mybatis-plus:
  type-aliases-package: com.zj.xyt.Entity
  mapper-locations: classpath:mapper/*.xml

